Feat/#11 bingsoontopping persistence layer
Team-BingsooChef/bingsoochef-api-server pull request #16
Opened 2024-08-21 09:10 UTC by wgwjh05169

### ✨ 작업 내용
---
- 빙수와 토핑에 JPA Entity와 Repository를 작성하였습니다.
- 프로그램 실행 시, 데이터베이스에 Topping type이 초기화 되지 않은 경우 초기화를 수행하는 코드를 작성하였습니다.

### ✨ 참고 사항
- MySQL 드라이버를 추가하였습니다. 이는 dev 배포 환경에도 적용해두었습니다.
- 하이버네이트의 권장 사항을 따르기 위해 Entity와 Embeddable, MappedSuperclass에 all open을 적용해두었습니다.

---

### ⏰ 현재 버그

x

---

### ✏ Git Close

close #11

2024-08-21 10:27 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/bingsoo/domain/Bingsoo.kt
> +    }
두 매서드를 오버라이딩 하신 이유가 있을까요?

2024-08-21 10:34 UTC, sanghee0820 requested changes
리뷰 한번 확인부탁드립니다~

2024-08-21 10:34 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/config/DatabaseInitialize.kt
> +}
굳이 코드상으로 DB를 초기화시켜줄 필요가 없을 것 같습니다.

2024-08-21 10:34 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/domain/Topping.kt
> +    var comment: Comment,
1:1 관계여서 엔티티로 나누는 것 보다,값객체로 두는게 좋아보이는데 어떻게 생각하세요?

2024-08-21 10:54 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/bingsoo/domain/Bingsoo.kt
> +    }
ORM을 사용할 때 @Id 컬럼의 값으로 비교할 수 있도록 오버라이딩 할 것을 권장한다고 알고 있습니다!
다만 이슈 없이 올바르게 오버라이딩 했는지는 테스트를 수행해야 하는데, 이는 하이버네이트 Proxy 객체나 지연 로딩에 대해 더 학습한 후 하고자 합니다..^^..
참고: https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#mapping-model-pojo-equalshashcode

2024-08-21 10:55 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/config/DatabaseInitialize.kt
> +}
더 선호하시는 방식이 있을까요?

2024-08-22 05:21 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/domain/Topping.kt
> +    var comment: Comment,
Comment가 Topping에 대한 정보와 관련이 없고, 추후에 기능이 더 생길 수 있음을 고려해 분리해두는 것이 더 좋아 보입니다!

2024-08-24 04:02 UTC, Catleap02 approved these changes

2024-08-24 04:03 UTC, merged