Feat/#4 swagger specific
Team-BingsooChef/bingsoochef-api-server pull request #19
Opened 2024-08-27 08:12 UTC by wgwjh05169

### ✨ 작업 내용

- 빙수와 토핑 목록 조회에 대한 API를 분리하였습니다.
- 토핑 조회 시 페이지네이션을 적용하였습니다.
---

### ✨ 참고 사항
- 쿼리 파라미터의 경우 URL에 직접 노출되는 것을 고려하여 파라미터의 이름을 약어로 작성하였습니다.

---

### ⏰ 현재 버그

x

---

### ✏ Git Close
x

2024-08-27 09:46 UTC, sanghee0820 requested changes
Pageable관련해서 수정 부탁드리게요

2024-08-27 09:46 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
> +    override fun getToppingPage(@RequestParam(value = "b") bingsooId: Long, @RequestParam(value = "p") page: Int): ResponseEntity<ToppingPageResponse> {
int형 변수를 사용하신 이유가있을까요?
Pageable를 사용하는게 더 좋아보입니다.

2024-08-27 17:15 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
> +    override fun getToppingPage(@RequestParam(value = "b") bingsooId: Long, @RequestParam(value = "p") page: Int): ResponseEntity<ToppingPageResponse> {
오랜만에 써서 까묵었어용

2024-08-28 04:19 UTC, sanghee0820 approved these changes
LGTM

2024-08-28 04:21 UTC, merged