Feat/#3 bingsoo api
Team-BingsooChef/bingsoochef-api-server pull request #20
Opened 2024-08-29 11:54 UTC by wgwjh05169

### ✨ 작업 내용
- 빙수 생성, 수정, 조회 API를 구현하였습니다.
- JPA 레포지토리 테스트를 수행하였습니다. (JPA Entity의 equals 오버라이딩 동작 확인)
- CustomException과 ExceptionHandler(RestControllerAdvice)를 작성하였습니다.

---

### ✨ 참고 사항
- 로그인 없이 user id를 받아 동작하며, User-Bingsoo 간 매핑이 이루어지지 않습니다.
- HTTP 메시지의 JSON 역직렬화 시 null 값을 대체하는 옵션을 끄고, HttpMessageNotReadableException에 대한 핸들링을 작성하였습니다. 클라이언트에서 파라미터를 누락하였을 때 API가 정상 동작하거나 잘못된 리소스 참조하는 일을 방지하기 위해 껐습니다.
- CustomException들이 많아지면 Enum으로 바꾸고 싶은데... 기회 되면 한 번 의논해보고 싶습니다.

---

### ⏰ 현재 버그
- test 수행 시 Given에서 save 호출한 후 When에서 find 호출한 경우 SQL 쿼리가 두 번 날아갑니다... (예상: 1번) 이후 영속성 테스트 수행 시 다시 확인해보려 합니다.

---

### ✏ Git Close
close #3

2024-08-29 13:40 UTC, sanghee0820 requested changes
Exception부분은, Enum이 좀 더 보기 편할 것 같다는 생각은 듭니다~!!!

몇가지 수정할만한 부분 남겼습니다 수정부탁드려요.

2024-08-29 13:40 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/bingsoo/application/BingsooService.kt
> +    fun getBingsoo(bingsooId: Long): Bingsoo {
Transactional을 class에 붙인것은 좋았는데, 이렇게되면 read 매서드에서도 Transaction이 적용되네요!!

2024-08-29 13:40 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/bingsoo/application/CreateBingsooCommand.kt
> +}
UpdateBingsooCommand랑 스타일 맞추어주세요!!

2024-08-29 13:40 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/bingsoo/domain/Taste.kt
> +//    }
쓸모없는 주석은 삭제해주세요!

2024-08-29 13:40 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/bingsoo/presentation/BingsooController.kt
> +        )
줄바꿈을 함으로 인해서 가독성이 좀 더 떨어지는 것 같아요

2024-08-29 14:05 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/bingsoo/application/BingsooService.kt
> +    fun getBingsoo(bingsooId: Long): Bingsoo {
아차차 ~ 감사합니다.

2024-08-30 11:56 UTC, sanghee0820 approved these changes
LGTM

2024-09-01 12:46 UTC, merged