Feat/#12 topping api
Team-BingsooChef/bingsoochef-api-server pull request #21
Opened 2024-09-03 10:20 UTC by wgwjh05169

### ✨ 작업 내용
- 토핑 생성 API를 구현하였습니다.

---

### ✨ 참고 사항
- 토핑 생성 API에 수정 사항이 있습니다.
- 토핑에 대한 API에 임시 사용자 ID를 추가하였습니다.
- 토핑에 대한 다른 API는 아직 구현 전이지만, 변경된 API를 스웨거에 반영하기 위해 먼저 PR 올립니다.
---

### ⏰ 현재 버그
X

---

### ✏ Git Close
X

2024-09-03 15:11 UTC, sanghee0820 reviewed
리뷰 확인 한번 부탁드립니다!

2024-09-03 15:11 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/application/CreateToppingCommand.kt
> +            if (quizType == QuizType.OX && (questions.isNullOrEmpty() || questions.size != 1 || (questions[0].first != "O" && questions[0].first != "X")))
이 부분을 매서드로 뺄 수 있을까요?
무슨 조건인지 알아보기 힘듭니다.

2024-09-03 15:11 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
> +                questions = request.quiz?.questions
Request의 매서드로 빼는것이 좋아보입니다.

2024-09-03 15:11 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
> +        val toppingResponse = ToppingResponse(topping = toppingDto, comment = null)
이 부분도 매서드로 뺄 수 있을것 같습니다.

2024-09-04 06:24 UTC, sanghee0820 requested changes
확인 부탁드립니다.

2024-09-04 06:24 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/application/CreateToppingCommand.kt
> +private fun isValidOX(questions : List<Pair<String, Boolean>>?)  {
리턴이 없으므로, validateOX 이 조금 더 직관적일 것 같스빈다.

2024-09-04 06:24 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/application/CreateToppingCommand.kt
> +private fun isValidMultipleChoice(questions: List<Pair<String, Boolean>>?)  {
동일합니다.

2024-09-04 06:24 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
> +        val command = CreateToppingCommand.of(request.userId, request)
\의존 방향이 Application -> Presentation으로 향해있는 것 같습니다.

2024-09-04 06:24 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
> +        val topping : Topping = toppingService.createTopping(command)
도메인이 컨트롤러까지 나와있네요.
Service -> Controller DTO를 추가하는게 좋아보입니다.

2024-09-04 06:24 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
> +        val toppingResponse = convertToToppingResponse(topping = topping, comment = null)
제가 말씀드린 매서드로 분리하는 것은 어떤가 하는 의미는
ToppingResponse = ToppingDTO + CommentDTO인 상태인데,
ToppingDto = Topping(Service -> Controller DTO입니다) 이라면,
ToppingDto => Topping으로 ToppingDTO를 만드는 static 매서드,
CommentDto => Comment로 CommentDto 만드는 static 매서드,
ToppingResponse => Topping과 Comment로, ToppingDto, CommentDto로 변환 후, ToppingResponse 만드는 Static 매서드 이런식으로 만들면 어떨까 하는 말이었습니다.

혹시 이해가 안간다면 말씀해주세요!

2024-09-04 06:24 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/req/ToppingDto.kt
>  data class ToppingDto(
ToppingDto가 Res, Req 두개에 있네요!

2024-09-04 07:18 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
> +        val topping : Topping = toppingService.createTopping(command)
영속 상태의 엔티티가 컨트롤러에서 변경 감지가 될 수 있겠네요 수정하겠습니다,,~

2024-09-04 07:29 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
> +        val toppingResponse = convertToToppingResponse(topping = topping, comment = null)
DTO 구성과 형 변환 과정에서 메소드 호출의 깊이가 깊어지는 것을 선호하지 않아 위와 같이 작성했습니다.
Kotlin의 nested class를 도입해보는 건 어떨지용

2024-09-04 07:34 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/req/ToppingDto.kt
>  data class ToppingDto(
Kotlin의 nested class를 도입해보는 건 어떨지용 22

2024-09-04 14:11 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
> +        val toppingResponse = convertToToppingResponse(topping = topping, comment = null)
죠습니다.

2024-09-04 14:14 UTC, sanghee0820 approved these changes
한결 보기 편해진 것 같습니다!!!
고생 많으셨습니다.

2024-09-04 14:14 UTC, merged