회원가입 기능을 구현했어요 ‼️
Team-BingsooChef/bingsoochef-api-server pull request #24
Opened 2024-09-07 14:16 UTC by sanghee0820

### ✨ 작업 내용

- 이메일 인증 기능을 추가했습니다.
- 이메일 인증코드 확인 기능을 추가했습니다.
- 회원가입 로직을 추가했습니다.

---

### ✨ 참고 사항

- 아직 로그인 기능은 구현되지 않았습니다.

---

### ⏰ 현재 버그

- 모릅니다!

---

### ✏ Git Close

2024-09-08 08:59 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/security/application/AuthenticationService.kt
> +            print(e.message)
표준 출력 대신 로거를 사용하는 건 어떠신가요?
추후에 파일 출력으로 변경할 때를 위해서도 필요할 것 같습니다!

2024-09-08 09:05 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/security/presentation/req/EmailRequest.kt
> +    val email: String
코틀린의 프로퍼티는 기본적으로 NotNull인데 @NotNull 검사가 필요할까요?
현재 ExceptionHandler에서 서블렛 매핑이나  JSON 역직렬화 시 발생하는 NPE를 핸들링 하고 있습니다.

2024-09-08 09:16 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/security/application/AuthenticationService.kt
> +            helper.setTo(email)
올바르지 않은 메일로 전송을 시도하고 오류를 반환하는 것이 시간이 좀 걸렸던 걸로 기억하는데, 메일 생성에 앞서 이메일 양식을 검사하는 조건이 추가되면 어떻까요?

2024-09-08 09:18 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/user/domain/User.kt
> +) {
이메일 속성이 빠진 것 같습니다!

2024-09-08 09:26 UTC, wgwjh05169 requested changes
리뷰 남긴 부분 확인 부탁드립니다!

2024-09-08 12:35 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/security/application/AuthenticationService.kt
> +            helper.setTo(email)
이건 메일 API Request에서, @Email 로 확인을 하고 있습니다!

2024-09-08 12:37 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/user/domain/User.kt
> +) {
일단 회원가입 로직만 구현해서 나중에 추가할 예정입니다.
추가로 이메일 => username 이고, 전화번호는 피그마 상에 없던데 필요할까요?

2024-09-08 12:38 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/security/application/AuthenticationService.kt
> +            helper.setTo(email)
아하~~ 좋아용 👍👍

2024-09-08 12:38 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/security/presentation/req/EmailRequest.kt
> +    val email: String
그러면 Null일 경우 에러 코드가 어떻게 될까요??
에러코드를 추가할 수 있을까요??
코틀린이 아직 어려워서 잘 모르겠습니당...

2024-09-08 12:38 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/security/application/AuthenticationService.kt
> +            print(e.message)
아 이부분은 제가 실수했습니다!! 수정하겠습니다.

2024-09-08 12:41 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/security/presentation/req/EmailRequest.kt
> +    val email: String
앗 제가 착각했어요..^^..!
dev에 있는 게 아니라 지금 제가 올린 PR이나 feat/#12-topping-api에서 확인하실 수 있습니다!

2024-09-08 12:44 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/user/domain/User.kt
> +) {
아하 알겠습니다.
필요없는 필드면 ERD에 수정이 필요할 것 같아요! 반영해주시면 감사하겠습니다 👍👍

2024-09-12 08:16 UTC, wgwjh05169 approved these changes
좋아요~!~!!

2024-09-14 11:11 UTC, merged