Feat/#4 swagger specific
Team-BingsooChef/bingsoochef-api-server pull request #9
Opened 2024-08-08 10:25 UTC by wgwjh05169

### ✨ 작업 내용
- Operation과 AprResponse로 스웨거 명세를 보충 작성하였습니다.
- 스웨거 명세 코드와 컨트롤러 코드를 구분하기 위해 인터페이스를 생성하였습니다.
- 스웨거 명세를 작성하며 URI 컨벤션과 Requset 오류를 수정하였습니다.

---

### ✨ 참고 사항
- 성공과 실패 시 응답 코드는 작성하면서 대략적으로 생각나는 케이스를 기반으로 명시하였습니다. 정확한 코드나 에러 문구 등은 추후에 수정될 수 있습니다!!

---

### ⏰ 현재 버그
X

---

### ✏ Git Close
X

2024-08-08 11:30 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/bingsoo/presentation/BingsooSwaggerInterface.kt
> +interface BingsooSwaggerInterface {
API도 여러 버전이 추후 존재 할 수 있어서 Swagger 네이밍은 굳이 안써도 될 것 같은데 어떻게 생각하시나요?
```suggestion
interface BongsooControllerInterface {
```

2024-08-08 11:31 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
>  @RequestMapping("/users/bingsoos/toppings")
앞에 버전같은 정보를 주가해주는건 어떨까요?
또 굳이 users가 필요한 이유가 있을까요?

```suggestion
@RequestMapping("/api/v1/bingsoos/toppings")
```

2024-08-08 11:32 UTC, sanghee0820 requested changes
확인한번 부탁드려요!

2024-08-10 04:06 UTC, wgwjh05169 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingController.kt
>  @RequestMapping("/users/bingsoos/toppings")
API Versioning은 프론트엔드 개발 시작 후에 다시 논의해봅시다!
URI는 빙수라는 자원을 사용자가 가지고 있는 관계라 이렇게 지었습니다.

2024-08-10 05:02 UTC, sanghee0820 commented on src/main/kotlin/bingsoochef/bingsoochef/toppping/presentation/ToppingControllerInterface.kt
> +interface ToppingControllerInterface {
LGTM

2024-08-10 05:03 UTC, sanghee0820 approved these changes
LGTM

2024-08-10 05:04 UTC, merged